// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb2456Epsmt2b_INveT4eJKR_3Z6NpM3s',
    appId: '1:178440710636:android:7e114cea4dd70bd477b8c9',
    messagingSenderId: '178440710636',
    projectId: 'kibotick-7be59',
    storageBucket: 'kibotick-7be59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTM0RMh8hpZPJXhv0DDvSRIHY649a6Y7g',
    appId: '1:178440710636:ios:846f0503ee2a73f277b8c9',
    messagingSenderId: '178440710636',
    projectId: 'kibotick-7be59',
    storageBucket: 'kibotick-7be59.appspot.com',
    iosBundleId: 'com.example.kibotick',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnMXQN_adhS4d8MlLi3o8HO1k4Vs1l7cY',
    appId: '1:178440710636:web:81eb159f5cbdfc8477b8c9',
    messagingSenderId: '178440710636',
    projectId: 'kibotick-7be59',
    authDomain: 'kibotick-7be59.firebaseapp.com',
    storageBucket: 'kibotick-7be59.appspot.com',
    measurementId: 'G-SJGCY8GVDF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTM0RMh8hpZPJXhv0DDvSRIHY649a6Y7g',
    appId: '1:178440710636:ios:846f0503ee2a73f277b8c9',
    messagingSenderId: '178440710636',
    projectId: 'kibotick-7be59',
    storageBucket: 'kibotick-7be59.appspot.com',
    iosBundleId: 'com.example.kibotick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnMXQN_adhS4d8MlLi3o8HO1k4Vs1l7cY',
    appId: '1:178440710636:web:718f3f356456c8d577b8c9',
    messagingSenderId: '178440710636',
    projectId: 'kibotick-7be59',
    authDomain: 'kibotick-7be59.firebaseapp.com',
    storageBucket: 'kibotick-7be59.appspot.com',
    measurementId: 'G-BEN8M04TFM',
  );

}